import { Component, OnInit } from '@angular/core';

@Component({
    selector: 'app-testimonial',
    templateUrl: './testimonial.component.html',
    styleUrls: ['./testimonial.component.scss']
})
export class TestimonialComponent implements OnInit {
    public testimonials = [
        { profile: "https://lambdacube.in/wp-content/uploads/2021/10/Shivansh-Agrawal.jpg", text:"Atmaram Sir is an excellent teacher! He provides both a great mix of listening, speaking and practical learning activities and a very safe, supportive learning environment. As a student, you feel pushed to learn and try out new competencies, feel supported in doing so and gain valuable lessons that help you to improve.", author: "Shivansh Agrawal", subHeading: "IIIT Lucknow - CS" },
        { profile: "https://lambdacube.in/wp-content/uploads/2021/01/Sarvesh-Mandewal.jpg", text:"I am extremely grateful to Pragyanand Sir & Snehanshu Sir for my selection in IIT-Roorkee. Their experiences were very valuable and helped me to clear my Physics & Chemistry concepts and boost my score. They always kept me motivated throughout my journey and hence I was able to achieve 7370 rank in JEE-Advance 2019. I hope their experience help many other students like me.", author: "Sarvesh Mandeval", subHeading: "JEE-Advanced (AIR 7370)", year: 2019},
        { profile: "https://lambdacube.in/wp-content/uploads/2021/01/Ankit.jpg", text: "I am really grateful to Snehanshu Sir for all the support and guidance he provided me while I was preparing for the competitive exams. His efforts really helped my Chemistry scores to improve. He has constantly motivated and encouraged me, especially when the exams were postponed due to Covid-19. He always took extra classes whenever I needed them and it was due to this extra help that I managed to get a good rank in the Advanced exam. I secured admission in BITS-Goa and also had the opportunity to join IIT-Roorkee, which I did not take. I will always be thankful to sir for all his help.", author: "Ankit Bhattacharya", subHeading: "JEE-Advanced (AIR 4047)", year: 2020},
        { profile: "https://lambdacube.in/wp-content/uploads/2021/10/Neeraj-Chavan.jpg", text: "Hello everyone myself Neeraj Chavan, I am currently pursuing MBBS 1st year from Rajiv Gandhi Medical College . I scored 567 marks in NEET 2020 , I scored 140 marks in physics and it could become possible only because of Milan sir, who taught me physics for 11th and 12th standard. He supported me in each and every step of my NEET journey especially in physics. I used to send my doubts to sir late night and sir used to reply within seconds. I understood each and every concept of physics only because of Milan sir. I feel blessed to study physics from one of the best teachers, Milan sir!", author: "Neeraj Chavan", subHeading: "MBBS, Rajiv Gandhi Medical College (NEET)", year: 2020 },
        { profile: "https://lambdacube.in/wp-content/uploads/2021/01/Harshita-Jogi.jpg", text: "Snehanshu sir is an incredible teacher. Due to his teaching methods chemistry turned from a subject I kept avoiding to a subject I enjoyed studying. This was all because of the short tricks and formulae he created to make all the difficult chapters easy to understand. He gave me a lot of practice on every chapter and answered all of my doubts immediately no matter what time of the day it was. He not only solved my chemistry doubts but also guided me in which books to refer to and how to approach them. I would really like to thank him for helping me score better in chemistry and hence improve my percentile in all entrance exams.", author: "Harshita Jogi", subHeading: "JEE-Mains", year: 2020 },
        { profile: "https://lambdacube.in/wp-content/uploads/2021/01/Kartikey-Verma.jpg", text: "Pragyanand sir guided me in understanding difficult topics of physics in 12th standard. He used to clear all my small doubts as well as big doubts. He helped me recognise my weak areas of Physics and helped in mastering these concepts. His sets of questions were always challenging and tricky which helped in making my concepts stronger. His short tricks and tips always helped me. His constant support and continuous guidance helped me in achieving my desired goal. Thank you", author: "Kartikey Verma", subHeading: "JEE-Mains", year: 2019 },
        { profile: "https://lambdacube.in/wp-content/uploads/2021/01/ghosh.jpg", text: "I took a drop after JEE 2017 under a lot of uncertainty and was low on confidence. But I got into the habit of practicing everyday without thinking much about it. That’s where Pragyanand Sir  helped me . He motivated me to keep going and try the difficult problems even if they meant grinding for hours, instead of giving up. He played a crucial part in initiating my preparation from scratch and helping me in being regular from the start. I cleared JEE Advanced 2018 and joined IIT Bombay to pursue B.Tech  in  Metallurgical Engineering and Material Science.", author: "Sneharagya Ghosh", subHeading: "JEE-Advanced (AIR 3050)", year: 2018 },
        { profile: "https://lambdacube.in/wp-content/uploads/2021/10/hardik-jain.jpg", text: "I was taught Physics by Milan sir for two complete years (2017-19) in my higher secondary while preparing for engineering entrance exams JEE(M & A), MHT-CET, BITSAT, etc. He has an excellent grasp on all the domains that is Mechanics, Electrodynamics, Thermodynamics, Waves & Oscillation, Optics and puts more effort into getting the basics clear in his students than just getting the problem solved. Though drawing diagrams was a weak department for sir then, the visualization and intuition of the problem I was able to develop under him remains unmatched. The most respectable thing about him is the dedication he puts into teaching us. Wish you the very best Milan sir and thanks for teaching me!", author: "Hardik Jain", subHeading: "BITS Pilani", year: 2019 },
        { profile: "https://lambdacube.in/wp-content/uploads/2021/10/Aaryan-Singh.jpg", text: "I am Aryan Singh(B. Tech Civil Engineering IIT-BHU, Varanasi). I got an AIR of 6443(Gen) in JEE-Advanced,2019. I was very fortunate to have Aatmaram Sir as a Chemistry faculty in our coaching. As far as the physical chemistry was concerned, Aatmaram Sir taught us in a precise and ordered manner and made sure that our doubts were cleared properly. For Inorganic Chemistry, Aatmaram Sir provided us with sufficient and to-the-point notes made by him which were enough for my JEE preparation. Furthermore, he emphasized a lot on problem solving. The best part which made it possible for me to excel in chemistry was his notes which were more than sufficient for my chemistry preparation.", author: "Aaryan Singh", subHeading: "Year: 2019" },
        { profile: "https://lambdacube.in/wp-content/uploads/2021/10/Apoorva.jpg", text: "I used to think that chemistry is all about cramming the formulae and by using this approach I faced no difficulty in solving JEE Mains problems, but I struggled to solve JEE Advanced problems because it required the concept. Aatmaram sir emphasized more on concept and used to derive those complex formulae from the very basic fundamental concepts. Another good thing about Sir is he never says no to any doubt and is always ready to explain until the topic is properly understood. I am thankful to Aatmaram sir for teaching me chemistry and for guiding me in my 2 years journey for IIT. I got in IIT BHU CIVIL Branch", author: "Apoorv", subHeading: "IIT BHU" },
    ];

    constructor() { }


    ngOnInit(): void {
    }

}
